name: Bloom Series
favicon: null
layout_spectrum: 0.3364741981495172
typography_spectrum: 0.5259340340271592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.31554713868536055
  lightness: 0.9450854903552681
  saturation: 0.6009268022608012
  rhythmicContrast: 0.9044699489604682
purpose: []
